# GitLeaks configuration for AndroidZen Pro
# Comprehensive secrets detection for all file types

title = "AndroidZen Pro Secrets Detection"
description = "Comprehensive secrets scanning configuration"

[extend]
# Use default gitleaks rules as base
useDefault = true

[[rules]]
id = "android-keystore-password"
description = "Android Keystore Password"
regex = '''(?i)(keystore[_-]?password|store[_-]?password|key[_-]?password)\s*[:=]\s*['""]?([a-zA-Z0-9!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\?]{8,})['""]?'''
tags = ["android", "password", "keystore"]
keywords = ["keystorePassword", "storePassword", "keyPassword"]

[[rules]]
id = "android-signing-key"
description = "Android App Signing Key"
regex = '''-----BEGIN PRIVATE KEY-----[A-Za-z0-9+/\s]+=*-----END PRIVATE KEY-----'''
tags = ["android", "private-key", "signing"]

[[rules]]
id = "firebase-config"
description = "Firebase Configuration"
regex = '''(?i)(firebase[_-]?api[_-]?key|firebase[_-]?project[_-]?id|firebase[_-]?app[_-]?id|firebase[_-]?sender[_-]?id)\s*[:=]\s*['""]?([a-zA-Z0-9\-_.]{10,})['""]?'''
tags = ["firebase", "api-key", "config"]
keywords = ["firebaseApiKey", "firebaseProjectId", "firebaseAppId"]

[[rules]]
id = "google-oauth-client"
description = "Google OAuth Client ID/Secret"
regex = '''(?i)(google[_-]?client[_-]?(id|secret)|oauth[_-]?client[_-]?(id|secret))\s*[:=]\s*['""]?([a-zA-Z0-9\-_.]{20,})['""]?'''
tags = ["google", "oauth", "client-id"]
keywords = ["clientId", "clientSecret", "googleClientId"]

[[rules]]
id = "adb-keys"
description = "ADB Private Keys"
regex = '''(?i)(adb[_-]?key|android[_-]?debug[_-]?key)\s*[:=]\s*['""]?([A-Za-z0-9+/=]{40,})['""]?'''
tags = ["adb", "android", "debug-key"]
keywords = ["adbkey", "debugkey"]

[[rules]]
id = "database-credentials"
description = "Database Connection Strings"
regex = '''(?i)(database[_-]?url|db[_-]?url|connection[_-]?string)\s*[:=]\s*['""]?(postgresql|mysql|mongodb|redis)://[^'""\s]+['""]?'''
tags = ["database", "connection-string"]
keywords = ["databaseUrl", "dbUrl", "connectionString"]

[[rules]]
id = "jwt-secret"
description = "JWT Secret Keys"
regex = '''(?i)(jwt[_-]?secret|jwt[_-]?key|access[_-]?token[_-]?secret)\s*[:=]\s*['""]?([a-zA-Z0-9!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\?]{32,})['""]?'''
tags = ["jwt", "secret", "token"]
keywords = ["jwtSecret", "accessTokenSecret", "jwtKey"]

[[rules]]
id = "encryption-keys"
description = "Encryption Keys"
regex = '''(?i)(encrypt[_-]?key|encryption[_-]?key|cipher[_-]?key|secret[_-]?key)\s*[:=]\s*['""]?([a-zA-Z0-9+/=]{24,})['""]?'''
tags = ["encryption", "key"]
keywords = ["encryptKey", "encryptionKey", "secretKey"]

[[rules]]
id = "api-tokens"
description = "Generic API Tokens"
regex = '''(?i)(api[_-]?token|auth[_-]?token|bearer[_-]?token|access[_-]?token)\s*[:=]\s*['""]?([a-zA-Z0-9\-_.]{20,})['""]?'''
tags = ["api", "token", "auth"]
keywords = ["apiToken", "authToken", "bearerToken", "accessToken"]

[[rules]]
id = "private-certificates"
description = "Private Certificates and Keys"
regex = '''-----BEGIN (RSA PRIVATE KEY|PRIVATE KEY|CERTIFICATE)-----[A-Za-z0-9+/\s]+=*-----END (RSA PRIVATE KEY|PRIVATE KEY|CERTIFICATE)-----'''
tags = ["certificate", "private-key"]

[[rules]]
id = "android-manifest-secrets"
description = "Android Manifest API Keys"
regex = '''<meta-data\s+android:name="[^"]*api[_-]?key[^"]*"\s+android:value="([a-zA-Z0-9\-_.]{15,})"'''
tags = ["android", "manifest", "api-key"]

[[rules]]
id = "hardcoded-passwords"
description = "Hardcoded Passwords"
regex = '''(?i)(password|passwd|pwd)\s*[:=]\s*['""]([a-zA-Z0-9!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\?]{6,})['""]'''
tags = ["password", "hardcoded"]
keywords = ["password", "passwd", "pwd"]

[[rules]]
id = "slack-tokens"
description = "Slack API Tokens"
regex = '''xox[baprs]-[0-9]{12}-[0-9]{12}-[a-zA-Z0-9]{24}'''
tags = ["slack", "api-token"]

[[rules]]
id = "github-tokens"
description = "GitHub Personal Access Tokens"
regex = '''gh[pousr]_[A-Za-z0-9_]{36}'''
tags = ["github", "personal-access-token"]

[[rules]]
id = "docker-credentials"
description = "Docker Registry Credentials"
regex = '''(?i)(docker[_-]?password|docker[_-]?token|registry[_-]?password)\s*[:=]\s*['""]?([a-zA-Z0-9!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\?]{8,})['""]?'''
tags = ["docker", "registry", "password"]
keywords = ["dockerPassword", "dockerToken", "registryPassword"]

# Global allowlist - patterns to ignore
[allowlist]
description = "Global allowlist for false positives"
regexes = [
    # Common false positives
    '''(?i)example\.com''',
    '''(?i)localhost''',
    '''(?i)127\.0\.0\.1''',
    '''(?i)password.*placeholder''',
    '''(?i)your[_-]?(api[_-]?key|token|secret)''',
    '''(?i)(test|demo|sample)[_-]?(key|token|secret)''',
    '''(?i)(fake|mock)[_-]?(password|key|token)''',
    
    # Documentation and templates
    '''(?i)<your[_-]?(api[_-]?key|token|secret)>''',
    '''(?i)\{\{[_a-zA-Z0-9\s]*\}\}''', # Template variables
    '''(?i)\$\{[_a-zA-Z0-9\s]*\}''',   # Environment variables
    
    # Version control and build files
    '''\.git/''',
    '''node_modules/''',
    '''\.venv/''',
    '''venv/''',
    '''build/''',
    '''dist/''',
    '''\.egg-info/''',
    '''__pycache__/''',
    
    # Common patterns that aren't secrets
    '''password.*=.*\*+''',           # Masked passwords
    '''password.*=.*x+''',            # Placeholder passwords
    '''(?i)null|none|empty|undefined''',
]

paths = [
    '''\.secrets\.baseline''',        # Secrets baseline file
    '''\.env\.example''',            # Example environment files
    '''\.env\.template''',           # Template environment files
    '''README\.md''',                # Documentation files
    '''CHANGELOG\.md''',
    '''LICENSE''',
    '''\.gitignore''',
    '''\.gitkeep''',
    '''\.github/''',                 # GitHub workflow files (may contain examples)
]

files = [
    '''(.*?)(jpg|gif|doc|pdf|bin)$''', # Binary files
]

# Path-specific rules
[allowlist.paths]
# Allow certain patterns in specific paths
"frontend/public/" = [
    '''(?i)(api[_-]?key|token)''',   # Public frontend may reference API keys in comments
]

"backend/tests/" = [
    '''(?i)(test|mock|fake)[_-]?(password|key|token|secret)''',
    '''password.*=.*test''',
]

"docs/" = [
    '''(?i)(example|sample|demo)[_-]?(key|token|secret|password)''',
]

"infrastructure/" = [
    '''(?i)placeholder''',
    '''(?i)your[_-]?(key|token|secret)''',
]
