"""Initial database schema

Revision ID: 98dc5a8a3732
Revises: 
Create Date: 2025-08-28 00:04:24.302467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98dc5a8a3732'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('android_version', sa.String(length=50), nullable=True),
    sa.Column('is_connected', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_device_id'), 'devices', ['device_id'], unique=True)
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_index(op.f('ix_devices_is_active'), 'devices', ['is_active'], unique=False)
    op.create_index(op.f('ix_devices_is_connected'), 'devices', ['is_connected'], unique=False)
    op.create_index(op.f('ix_devices_serial_number'), 'devices', ['serial_number'], unique=True)
    op.create_table('optimization_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('profile_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('cpu_governor', sa.String(length=50), nullable=True),
    sa.Column('cpu_max_frequency', sa.Integer(), nullable=True),
    sa.Column('cpu_min_frequency', sa.Integer(), nullable=True),
    sa.Column('brightness_level', sa.Integer(), nullable=True),
    sa.Column('screen_timeout', sa.Integer(), nullable=True),
    sa.Column('adaptive_brightness', sa.Boolean(), nullable=True),
    sa.Column('wifi_optimization', sa.Boolean(), nullable=True),
    sa.Column('mobile_data_limit', sa.Integer(), nullable=True),
    sa.Column('background_data_restriction', sa.Boolean(), nullable=True),
    sa.Column('battery_saver_enabled', sa.Boolean(), nullable=True),
    sa.Column('doze_mode_enabled', sa.Boolean(), nullable=True),
    sa.Column('app_standby_enabled', sa.Boolean(), nullable=True),
    sa.Column('background_app_limit', sa.Integer(), nullable=True),
    sa.Column('animation_scale', sa.Float(), nullable=True),
    sa.Column('force_gpu_rendering', sa.Boolean(), nullable=True),
    sa.Column('hardware_acceleration', sa.Boolean(), nullable=True),
    sa.Column('auto_cache_clear', sa.Boolean(), nullable=True),
    sa.Column('cache_clear_interval', sa.Integer(), nullable=True),
    sa.Column('storage_cleanup_enabled', sa.Boolean(), nullable=True),
    sa.Column('storage_threshold', sa.Integer(), nullable=True),
    sa.Column('app_verification_enabled', sa.Boolean(), nullable=True),
    sa.Column('unknown_sources_allowed', sa.Boolean(), nullable=True),
    sa.Column('auto_security_updates', sa.Boolean(), nullable=True),
    sa.Column('advanced_settings', sa.JSON(), nullable=True),
    sa.Column('times_applied', sa.Integer(), nullable=True),
    sa.Column('last_applied', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effectiveness_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_profiles_id'), 'optimization_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_optimization_profiles_is_active'), 'optimization_profiles', ['is_active'], unique=False)
    op.create_index(op.f('ix_optimization_profiles_name'), 'optimization_profiles', ['name'], unique=False)
    op.create_index(op.f('ix_optimization_profiles_profile_type'), 'optimization_profiles', ['profile_type'], unique=False)
    op.create_table('threat_intelligence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('threat_type', sa.String(length=50), nullable=False),
    sa.Column('threat_name', sa.String(length=200), nullable=True),
    sa.Column('threat_family', sa.String(length=100), nullable=True),
    sa.Column('ioc_type', sa.String(length=50), nullable=False),
    sa.Column('ioc_value', sa.String(length=500), nullable=False),
    sa.Column('ioc_description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severitylevel'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('reputation_score', sa.Float(), nullable=True),
    sa.Column('intelligence_source', sa.String(length=100), nullable=True),
    sa.Column('source_reliability', sa.String(length=20), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('tlp_marking', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('detection_count', sa.Integer(), nullable=True),
    sa.Column('last_detected', sa.DateTime(timezone=True), nullable=True),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('related_threats', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_intelligence_id'), 'threat_intelligence', ['id'], unique=False)
    op.create_index(op.f('ix_threat_intelligence_ioc_type'), 'threat_intelligence', ['ioc_type'], unique=False)
    op.create_index(op.f('ix_threat_intelligence_ioc_value'), 'threat_intelligence', ['ioc_value'], unique=False)
    op.create_index(op.f('ix_threat_intelligence_is_active'), 'threat_intelligence', ['is_active'], unique=False)
    op.create_index(op.f('ix_threat_intelligence_severity'), 'threat_intelligence', ['severity'], unique=False)
    op.create_index(op.f('ix_threat_intelligence_threat_family'), 'threat_intelligence', ['threat_family'], unique=False)
    op.create_index(op.f('ix_threat_intelligence_threat_type'), 'threat_intelligence', ['threat_type'], unique=False)
    op.create_table('analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('metric_category', sa.String(length=50), nullable=True),
    sa.Column('cpu_usage', sa.Float(), nullable=True),
    sa.Column('memory_usage', sa.Float(), nullable=True),
    sa.Column('memory_available', sa.Integer(), nullable=True),
    sa.Column('memory_total', sa.Integer(), nullable=True),
    sa.Column('storage_used', sa.Integer(), nullable=True),
    sa.Column('storage_available', sa.Integer(), nullable=True),
    sa.Column('storage_total', sa.Integer(), nullable=True),
    sa.Column('storage_usage_percentage', sa.Float(), nullable=True),
    sa.Column('battery_level', sa.Integer(), nullable=True),
    sa.Column('battery_temperature', sa.Float(), nullable=True),
    sa.Column('battery_voltage', sa.Float(), nullable=True),
    sa.Column('battery_health', sa.String(length=20), nullable=True),
    sa.Column('charging_status', sa.String(length=20), nullable=True),
    sa.Column('network_type', sa.String(length=20), nullable=True),
    sa.Column('network_strength', sa.Integer(), nullable=True),
    sa.Column('data_received', sa.Integer(), nullable=True),
    sa.Column('data_transmitted', sa.Integer(), nullable=True),
    sa.Column('app_count_total', sa.Integer(), nullable=True),
    sa.Column('app_count_system', sa.Integer(), nullable=True),
    sa.Column('app_count_user', sa.Integer(), nullable=True),
    sa.Column('running_processes', sa.Integer(), nullable=True),
    sa.Column('cpu_temperature', sa.Float(), nullable=True),
    sa.Column('gpu_temperature', sa.Float(), nullable=True),
    sa.Column('thermal_state', sa.String(length=20), nullable=True),
    sa.Column('performance_score', sa.Float(), nullable=True),
    sa.Column('optimization_score', sa.Float(), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('additional_metrics', sa.JSON(), nullable=True),
    sa.Column('collection_method', sa.String(length=50), nullable=True),
    sa.Column('data_source', sa.String(length=100), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_device_id'), 'analytics', ['device_id'], unique=False)
    op.create_index(op.f('ix_analytics_id'), 'analytics', ['id'], unique=False)
    op.create_index(op.f('ix_analytics_is_anomaly'), 'analytics', ['is_anomaly'], unique=False)
    op.create_index(op.f('ix_analytics_metric_category'), 'analytics', ['metric_category'], unique=False)
    op.create_index(op.f('ix_analytics_metric_type'), 'analytics', ['metric_type'], unique=False)
    op.create_index(op.f('ix_analytics_recorded_at'), 'analytics', ['recorded_at'], unique=False)
    op.create_table('device_connection_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('connection_type', sa.String(length=20), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('session_duration', sa.Integer(), nullable=True),
    sa.Column('connection_quality', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('additional_info', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_connection_history_device_id'), 'device_connection_history', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_connection_history_id'), 'device_connection_history', ['id'], unique=False)
    op.create_index(op.f('ix_device_connection_history_timestamp'), 'device_connection_history', ['timestamp'], unique=False)
    op.create_table('profile_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('applied_by', sa.String(length=100), nullable=True),
    sa.Column('application_method', sa.String(length=50), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('settings_changed', sa.JSON(), nullable=True),
    sa.Column('before_performance_score', sa.Float(), nullable=True),
    sa.Column('after_performance_score', sa.Float(), nullable=True),
    sa.Column('performance_improvement', sa.Float(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reverted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['optimization_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_applications_applied_at'), 'profile_applications', ['applied_at'], unique=False)
    op.create_index(op.f('ix_profile_applications_device_id'), 'profile_applications', ['device_id'], unique=False)
    op.create_index(op.f('ix_profile_applications_id'), 'profile_applications', ['id'], unique=False)
    op.create_index(op.f('ix_profile_applications_profile_id'), 'profile_applications', ['profile_id'], unique=False)
    op.create_table('security_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_category', sa.String(length=50), nullable=True),
    sa.Column('event_title', sa.String(length=200), nullable=False),
    sa.Column('event_description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severitylevel'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'INVESTIGATING', 'RESOLVED', 'FALSE_POSITIVE', 'IGNORED', name='eventstatus'), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.Column('detection_method', sa.String(length=50), nullable=True),
    sa.Column('source_component', sa.String(length=100), nullable=True),
    sa.Column('source_data', sa.JSON(), nullable=True),
    sa.Column('app_package_name', sa.String(length=255), nullable=True),
    sa.Column('app_name', sa.String(length=200), nullable=True),
    sa.Column('app_version', sa.String(length=50), nullable=True),
    sa.Column('app_permissions', sa.JSON(), nullable=True),
    sa.Column('network_address', sa.String(length=45), nullable=True),
    sa.Column('network_port', sa.Integer(), nullable=True),
    sa.Column('network_protocol', sa.String(length=20), nullable=True),
    sa.Column('network_data_size', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_permissions', sa.String(length=20), nullable=True),
    sa.Column('system_process', sa.String(length=200), nullable=True),
    sa.Column('system_user', sa.String(length=100), nullable=True),
    sa.Column('system_command', sa.Text(), nullable=True),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_lon', sa.Float(), nullable=True),
    sa.Column('location_accuracy', sa.Float(), nullable=True),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('auto_response_taken', sa.Boolean(), nullable=True),
    sa.Column('response_actions', sa.JSON(), nullable=True),
    sa.Column('mitigation_steps', sa.Text(), nullable=True),
    sa.Column('is_mitigated', sa.Boolean(), nullable=True),
    sa.Column('threat_indicators', sa.JSON(), nullable=True),
    sa.Column('behavioral_patterns', sa.JSON(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('event_count', sa.Integer(), nullable=True),
    sa.Column('last_occurrence', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_occurrence', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('investigated_by', sa.String(length=100), nullable=True),
    sa.Column('investigation_notes', sa.Text(), nullable=True),
    sa.Column('investigation_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('investigation_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolution_action', sa.String(length=100), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_events_app_package_name'), 'security_events', ['app_package_name'], unique=False)
    op.create_index(op.f('ix_security_events_detected_at'), 'security_events', ['detected_at'], unique=False)
    op.create_index(op.f('ix_security_events_device_id'), 'security_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_security_events_event_category'), 'security_events', ['event_category'], unique=False)
    op.create_index(op.f('ix_security_events_event_type'), 'security_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_security_events_id'), 'security_events', ['id'], unique=False)
    op.create_index(op.f('ix_security_events_is_recurring'), 'security_events', ['is_recurring'], unique=False)
    op.create_index(op.f('ix_security_events_severity'), 'security_events', ['severity'], unique=False)
    op.create_index(op.f('ix_security_events_status'), 'security_events', ['status'], unique=False)
    op.create_table('storage_trends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('avg_storage_used', sa.Float(), nullable=True),
    sa.Column('max_storage_used', sa.Float(), nullable=True),
    sa.Column('min_storage_used', sa.Float(), nullable=True),
    sa.Column('storage_change', sa.Float(), nullable=True),
    sa.Column('storage_change_percentage', sa.Float(), nullable=True),
    sa.Column('app_data_size', sa.Integer(), nullable=True),
    sa.Column('system_data_size', sa.Integer(), nullable=True),
    sa.Column('cache_size', sa.Integer(), nullable=True),
    sa.Column('media_size', sa.Integer(), nullable=True),
    sa.Column('trend_direction', sa.String(length=20), nullable=True),
    sa.Column('growth_rate', sa.Float(), nullable=True),
    sa.Column('predicted_full_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_points', sa.Integer(), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_trends_device_id'), 'storage_trends', ['device_id'], unique=False)
    op.create_index(op.f('ix_storage_trends_id'), 'storage_trends', ['id'], unique=False)
    op.create_index(op.f('ix_storage_trends_period_start'), 'storage_trends', ['period_start'], unique=False)
    op.create_index(op.f('ix_storage_trends_period_type'), 'storage_trends', ['period_type'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('theme', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=True),
    sa.Column('alert_thresholds', sa.JSON(), nullable=True),
    sa.Column('notification_frequency', sa.String(length=20), nullable=True),
    sa.Column('auto_monitoring_enabled', sa.Boolean(), nullable=True),
    sa.Column('monitoring_interval', sa.Integer(), nullable=True),
    sa.Column('detailed_logging', sa.Boolean(), nullable=True),
    sa.Column('optimization_profile_id', sa.Integer(), nullable=True),
    sa.Column('auto_optimization', sa.Boolean(), nullable=True),
    sa.Column('optimization_schedule', sa.JSON(), nullable=True),
    sa.Column('dashboard_layout', sa.JSON(), nullable=True),
    sa.Column('chart_preferences', sa.JSON(), nullable=True),
    sa.Column('data_retention_days', sa.Integer(), nullable=True),
    sa.Column('require_confirmation', sa.Boolean(), nullable=True),
    sa.Column('auto_backup_settings', sa.Boolean(), nullable=True),
    sa.Column('privacy_mode', sa.Boolean(), nullable=True),
    sa.Column('refresh_rate', sa.Integer(), nullable=True),
    sa.Column('animation_enabled', sa.Boolean(), nullable=True),
    sa.Column('sound_enabled', sa.Boolean(), nullable=True),
    sa.Column('advanced_preferences', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['optimization_profile_id'], ['optimization_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_settings_device_id'), 'user_settings', ['device_id'], unique=False)
    op.create_index(op.f('ix_user_settings_id'), 'user_settings', ['id'], unique=False)
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=False)
    op.create_table('security_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('security_event_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('alert_title', sa.String(length=200), nullable=False),
    sa.Column('alert_message', sa.Text(), nullable=False),
    sa.Column('alert_priority', sa.String(length=20), nullable=True),
    sa.Column('recipient_type', sa.String(length=20), nullable=True),
    sa.Column('recipient_id', sa.String(length=100), nullable=True),
    sa.Column('recipient_address', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('delivery_attempts', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('is_automatic', sa.Boolean(), nullable=True),
    sa.Column('suppress_similar', sa.Boolean(), nullable=True),
    sa.Column('expiry_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_required', sa.Boolean(), nullable=True),
    sa.Column('response_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_received', sa.Boolean(), nullable=True),
    sa.Column('response_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['security_event_id'], ['security_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_alerts_alert_type'), 'security_alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_security_alerts_id'), 'security_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_security_alerts_security_event_id'), 'security_alerts', ['security_event_id'], unique=False)
    op.create_index(op.f('ix_security_alerts_status'), 'security_alerts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_alerts_status'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_security_event_id'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_id'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_alert_type'), table_name='security_alerts')
    op.drop_table('security_alerts')
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.drop_index(op.f('ix_user_settings_id'), table_name='user_settings')
    op.drop_index(op.f('ix_user_settings_device_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_storage_trends_period_type'), table_name='storage_trends')
    op.drop_index(op.f('ix_storage_trends_period_start'), table_name='storage_trends')
    op.drop_index(op.f('ix_storage_trends_id'), table_name='storage_trends')
    op.drop_index(op.f('ix_storage_trends_device_id'), table_name='storage_trends')
    op.drop_table('storage_trends')
    op.drop_index(op.f('ix_security_events_status'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_severity'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_is_recurring'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_id'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_event_type'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_event_category'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_device_id'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_detected_at'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_app_package_name'), table_name='security_events')
    op.drop_table('security_events')
    op.drop_index(op.f('ix_profile_applications_profile_id'), table_name='profile_applications')
    op.drop_index(op.f('ix_profile_applications_id'), table_name='profile_applications')
    op.drop_index(op.f('ix_profile_applications_device_id'), table_name='profile_applications')
    op.drop_index(op.f('ix_profile_applications_applied_at'), table_name='profile_applications')
    op.drop_table('profile_applications')
    op.drop_index(op.f('ix_device_connection_history_timestamp'), table_name='device_connection_history')
    op.drop_index(op.f('ix_device_connection_history_id'), table_name='device_connection_history')
    op.drop_index(op.f('ix_device_connection_history_device_id'), table_name='device_connection_history')
    op.drop_table('device_connection_history')
    op.drop_index(op.f('ix_analytics_recorded_at'), table_name='analytics')
    op.drop_index(op.f('ix_analytics_metric_type'), table_name='analytics')
    op.drop_index(op.f('ix_analytics_metric_category'), table_name='analytics')
    op.drop_index(op.f('ix_analytics_is_anomaly'), table_name='analytics')
    op.drop_index(op.f('ix_analytics_id'), table_name='analytics')
    op.drop_index(op.f('ix_analytics_device_id'), table_name='analytics')
    op.drop_table('analytics')
    op.drop_index(op.f('ix_threat_intelligence_threat_type'), table_name='threat_intelligence')
    op.drop_index(op.f('ix_threat_intelligence_threat_family'), table_name='threat_intelligence')
    op.drop_index(op.f('ix_threat_intelligence_severity'), table_name='threat_intelligence')
    op.drop_index(op.f('ix_threat_intelligence_is_active'), table_name='threat_intelligence')
    op.drop_index(op.f('ix_threat_intelligence_ioc_value'), table_name='threat_intelligence')
    op.drop_index(op.f('ix_threat_intelligence_ioc_type'), table_name='threat_intelligence')
    op.drop_index(op.f('ix_threat_intelligence_id'), table_name='threat_intelligence')
    op.drop_table('threat_intelligence')
    op.drop_index(op.f('ix_optimization_profiles_profile_type'), table_name='optimization_profiles')
    op.drop_index(op.f('ix_optimization_profiles_name'), table_name='optimization_profiles')
    op.drop_index(op.f('ix_optimization_profiles_is_active'), table_name='optimization_profiles')
    op.drop_index(op.f('ix_optimization_profiles_id'), table_name='optimization_profiles')
    op.drop_table('optimization_profiles')
    op.drop_index(op.f('ix_devices_serial_number'), table_name='devices')
    op.drop_index(op.f('ix_devices_is_connected'), table_name='devices')
    op.drop_index(op.f('ix_devices_is_active'), table_name='devices')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_id'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
