# Service Integrations Configuration
# Real services and accounts integration for comprehensive testing

integrations:
  name: "AndroidZen Service Integrations"
  version: "1.0"

# Google Zero Touch Enrollment
google_zero_touch:
  enabled: true
  environment: "production"  # Use real production environment
  portal_url: "https://partner.android.com/zerotouch"
  organization_id: "{{GOOGLE_ZTE_ORG_ID}}"
  partner_id: "{{GOOGLE_ZTE_PARTNER_ID}}"
  
  api_configuration:
    endpoint: "https://androiddeviceprovisioning.googleapis.com/v1"
    scopes:
      - "https://www.googleapis.com/auth/androiddeviceprovisioning"
    service_account_key: "{{GOOGLE_ZTE_SERVICE_ACCOUNT_KEY}}"
    
  device_configurations:
    - name: "enterprise-config"
      dpc_package: "com.androidzen.dpc"
      dpc_extras:
        server_url: "{{ANDROIDZEN_SERVER_URL}}"
        enrollment_token: "{{ENROLLMENT_TOKEN}}"
        
    - name: "kiosk-config" 
      dpc_package: "com.androidzen.kiosk"
      dpc_extras:
        kiosk_app: "com.example.kioskapp"
        exit_disabled: "true"
        
  test_scenarios:
    - name: "zero_touch_enrollment"
      description: "Test automatic enrollment of new devices"
      devices: ["samsung-s23-001", "pixel-8-001"]
      expected_outcome: "Device automatically enrolled and configured"
      
    - name: "factory_reset_recovery"
      description: "Test re-enrollment after factory reset"
      devices: ["samsung-s22-001"]
      steps:
        - factory_reset
        - verify_auto_enrollment
        - verify_policy_application

# Managed Google Play
managed_google_play:
  enabled: true
  enterprise_id: "{{MANAGED_PLAY_ENTERPRISE_ID}}"
  service_account: "{{MANAGED_PLAY_SERVICE_ACCOUNT}}"
  
  api_configuration:
    endpoint: "https://www.googleapis.com/auth/androidenterprise"
    scopes:
      - "https://www.googleapis.com/auth/androidenterprise"
    credentials_file: "{{MANAGED_PLAY_CREDENTIALS_FILE}}"
    
  iframe_configuration:
    iframe_url: "https://play.google.com/work/apps"
    locale: "en_US"
    
  app_management:
    approved_apps:
      - package_name: "com.google.android.apps.docs"
        title: "Google Docs"
        auto_install: true
        
      - package_name: "com.microsoft.office.outlook"
        title: "Microsoft Outlook"
        auto_install: false
        
      - package_name: "com.slack"
        title: "Slack"
        auto_install: true
        permissions:
          - "android.permission.CAMERA"
          - "android.permission.MICROPHONE"
          
    private_apps:
      - package_name: "com.androidzen.enterprise"
        title: "AndroidZen Enterprise"
        apk_url: "{{PRIVATE_APP_APK_URL}}"
        
  test_scenarios:
    - name: "app_installation"
      description: "Test managed app installation"
      apps: ["com.google.android.apps.docs"]
      devices: ["pixel-7-001", "samsung-s21-001"]
      
    - name: "app_permissions"
      description: "Test app permission management"
      apps: ["com.slack"]
      devices: ["pixel-6-001"]

# Firebase Cloud Messaging
firebase_cloud_messaging:
  enabled: true
  project_id: "{{FCM_PROJECT_ID}}"
  sender_id: "{{FCM_SENDER_ID}}"
  server_key: "{{FCM_SERVER_KEY}}"
  
  api_configuration:
    endpoint: "https://fcm.googleapis.com/fcm/send"
    legacy_endpoint: "https://android.googleapis.com/gcm/send"
    
  message_types:
    - type: "notification"
      priority: "high"
      collapse_key: "device_command"
      
    - type: "data"
      priority: "normal"
      time_to_live: 86400
      
  test_scenarios:
    - name: "notification_delivery"
      description: "Test push notification delivery"
      message_type: "notification"
      devices: ["samsung-s23-001", "pixel-8-001", "xiaomi-13-001"]
      payload:
        title: "Test Notification"
        body: "This is a test notification from AndroidZen"
        
    - name: "data_message"
      description: "Test data message handling"
      message_type: "data"
      devices: ["oneplus-11-001"]
      payload:
        action: "sync_policies"
        timestamp: "{{CURRENT_TIMESTAMP}}"
        
    - name: "topic_messaging"
      description: "Test topic-based messaging"
      topic: "enterprise_devices"
      devices: ["samsung-s22-001", "moto-g84-001"]

# SSO Providers Integration
sso_providers:
  okta:
    enabled: true
    domain: "{{OKTA_DOMAIN}}"
    client_id: "{{OKTA_CLIENT_ID}}"
    client_secret: "{{OKTA_CLIENT_SECRET}}"
    
    api_configuration:
      base_url: "https://{{OKTA_DOMAIN}}.okta.com"
      endpoints:
        authorize: "/oauth2/v1/authorize"
        token: "/oauth2/v1/token"
        userinfo: "/oauth2/v1/userinfo"
        
    saml_configuration:
      entity_id: "http://www.okta.com/{{OKTA_APP_ID}}"
      sso_url: "https://{{OKTA_DOMAIN}}.okta.com/app/{{OKTA_APP_ID}}/sso/saml"
      certificate: "{{OKTA_CERTIFICATE}}"
      
    test_scenarios:
      - name: "oauth_login"
        description: "Test OAuth authentication flow"
        users: ["test.user@company.com"]
        devices: ["pixel-8-001"]
        
      - name: "saml_sso"
        description: "Test SAML SSO integration"
        users: ["admin@company.com"]
        devices: ["samsung-s23-001"]
        
  azure_ad:
    enabled: true
    tenant_id: "{{AZURE_TENANT_ID}}"
    client_id: "{{AZURE_CLIENT_ID}}"
    client_secret: "{{AZURE_CLIENT_SECRET}}"
    
    api_configuration:
      authority: "https://login.microsoftonline.com/{{AZURE_TENANT_ID}}"
      graph_endpoint: "https://graph.microsoft.com/v1.0"
      
    conditional_access:
      enabled: true
      policies:
        - name: "require_managed_device"
          conditions: ["device_compliance"]
          
    test_scenarios:
      - name: "conditional_access"
        description: "Test conditional access with device compliance"
        users: ["compliance.user@company.com"]
        devices: ["pixel-7-001"]
        
      - name: "intune_integration"
        description: "Test Microsoft Intune integration"
        users: ["intune.admin@company.com"]
        devices: ["samsung-s22-001"]

# Certificate Authorities
certificate_authorities:
  internal_ca:
    enabled: true
    ca_name: "AndroidZen Internal CA"
    ca_certificate: "{{INTERNAL_CA_CERT}}"
    ca_private_key: "{{INTERNAL_CA_KEY}}"
    
    certificate_types:
      - type: "device_identity"
        validity_days: 365
        key_size: 2048
        
      - type: "wifi_authentication"
        validity_days: 180
        key_size: 2048
        
    test_scenarios:
      - name: "certificate_deployment"
        description: "Test certificate installation on devices"
        certificate_type: "device_identity"
        devices: ["samsung-s23-001", "pixel-8-001"]
        
      - name: "certificate_renewal"
        description: "Test automatic certificate renewal"
        devices: ["samsung-s21-001"]
        
  public_ca:
    enabled: true
    provider: "lets_encrypt"
    acme_endpoint: "https://acme-v02.api.letsencrypt.org/directory"
    email: "{{LETSENCRYPT_EMAIL}}"
    
    domains:
      - "androidzen-staging.example.com"
      - "androidzen-api.example.com"
      
# Remote Control Gateway
remote_control_gateway:
  enabled: true
  provider: "teamviewer"  # or "anydesk", "chrome_remote_desktop"
  
  teamviewer:
    api_token: "{{TEAMVIEWER_API_TOKEN}}"
    company_id: "{{TEAMVIEWER_COMPANY_ID}}"
    
    device_configuration:
      unattended_access: true
      password_protection: true
      custom_quicksupport: true
      
  chrome_remote_desktop:
    enabled: true
    oauth_client_id: "{{CRD_OAUTH_CLIENT_ID}}"
    oauth_client_secret: "{{CRD_OAUTH_CLIENT_SECRET}}"
    
  vnc_server:
    enabled: true
    port: 5900
    password: "{{VNC_PASSWORD}}"
    encryption: true
    
  test_scenarios:
    - name: "remote_access"
      description: "Test remote device access"
      devices: ["samsung-s23-001", "pixel-8-001"]
      actions:
        - "connect"
        - "navigate_ui"
        - "execute_commands"
        - "disconnect"
        
    - name: "screen_sharing"
      description: "Test screen sharing functionality"
      devices: ["moto-g84-001"]
      duration: "5m"

# Enterprise Mobility Management
emm_integration:
  microsoft_intune:
    enabled: true
    tenant_id: "{{INTUNE_TENANT_ID}}"
    app_id: "{{INTUNE_APP_ID}}"
    app_secret: "{{INTUNE_APP_SECRET}}"
    
    policies:
      - name: "security_baseline"
        type: "device_compliance"
        settings:
          require_device_encryption: true
          require_screen_lock: true
          max_password_age: 90
          
  vmware_workspace_one:
    enabled: false  # Enable if using VMware
    server_url: "{{WORKSPACE_ONE_SERVER}}"
    api_key: "{{WORKSPACE_ONE_API_KEY}}"
    username: "{{WORKSPACE_ONE_USERNAME}}"
    password: "{{WORKSPACE_ONE_PASSWORD}}"

# Monitoring and Analytics
monitoring_integrations:
  google_analytics:
    enabled: true
    tracking_id: "{{GA_TRACKING_ID}}"
    measurement_id: "{{GA_MEASUREMENT_ID}}"
    
  crashlytics:
    enabled: true
    app_id: "{{CRASHLYTICS_APP_ID}}"
    
  new_relic:
    enabled: true
    app_token: "{{NEW_RELIC_APP_TOKEN}}"
    license_key: "{{NEW_RELIC_LICENSE_KEY}}"

# Testing Framework Integration
testing_frameworks:
  appium:
    enabled: true
    hub_url: "http://localhost:4444/wd/hub"
    capabilities:
      platformName: "Android"
      automationName: "UiAutomator2"
      
  espresso:
    enabled: true
    test_orchestrator: true
    
  ui_automator:
    enabled: true
    version: "2.2.0"
